version: '3.8'

services:
  database:
    extends:
      file: docker-compose.yml
      service: database

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: case_management_backend
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://app_user:app_password@database:3306/case_management
      - SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=dev-jwt-secret-key
      - CORS_ORIGINS=http://localhost:5173,http://frontend:5173
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - case_management_network
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        flask db upgrade &&
        flask run
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: case_management_frontend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - case_management_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 120s
      timeout: 10s
      retries: 2

volumes:
  mysql_data:
    driver: local

networks:
  case_management_network:
    driver: bridge